### ISSUE TITLE
Incorrect forwarding with reverse proxy after callback

### ISSUE THREAD

**Issue by sebsgr** [auth0/express-openid-connect#475]
### Checklist

- [X] The issue can be reproduced in the [express-openid-connect sample app](https://github.com/auth0-samples/auth0-express-webapp-sample/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/express-openid-connect#readme), [Examples](https://github.com/auth0/express-openid-connect/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/express-openid-connect/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/express-openid-connect/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/express-openid-connect/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

My Configuration:

```
expressWebserver.use(auth({
            baseURL: "https://demo.domain.com/app",
            clientID: "XXX",
            issuerBaseURL: "gitlab.xxx.com",  # Own GitLab as OIDC Provider
            secret: "XXX",
            authorizationParams: {
                response_type: 'code',
                scope: 'openid profile email api write_repository'
            }
        }));
```

Browser Request:

```
URL: https://demo.domain.de/app/callback?code=xxxxxx&state=xxxxx
Method: GET
Code: 302 
Remoteadresse: xxxx
content-length: 132
content-type: text/html; charset=utf-8
location: /test
```
As we can see the request to `https://demo.domain.de/app/callback` will result in a redirection to `/test`.
my expectation was it a forwarding to `/app/test` or `https://demo.domain.de/app/test`

### Reproduction

1. Build Docker Image for the application
```
FROM node:18-alpine as builder
WORKDIR /usr
COPY package*.json ./
COPY tsconfig.json ./
RUN npm config set strict-ssl false
RUN npm install
COPY src ./src
RUN npm run build

FROM node:18-alpine
WORKDIR /usr
COPY package*.json ./
RUN npm config set strict-ssl false
RUN npm install --only=production
COPY --from=builder /usr/dist .
EXPOSE 3000
CMD ["node", "app.js"]
```
2. Run Container with Treafik
```
  mfx-gitlab-bot:
    image: xxx
    labels:
      traefik.enable: true
      # HTTPS
      traefik.http.routers.app-https.rule: Host(`demo.domain.com`) && PathPrefix(`/app`)
      traefik.http.routers.app-https.entrypoints: websecure
      traefik.http.routers.app-https.tls: true
      traefik.http.routers.app-https.middlewares: mfx-gitlab-bot-pathreplace
      traefik.http.services.app-https.loadbalancer.server.port: 3000

      traefik.http.routers.app-http.service: mfx-gitlab-bot-https
      traefik.http.routers.app-https.service: mfx-gitlab-bot-https

      traefik.http.middlewares.app-pathreplace.replacepathregex.regex: "^/app/(.*)"
      traefik.http.middlewares.app-pathreplace.replacepathregex.replacement: "/$$1"
    networks:
      - proxy

```
3. Call a route e.g. 'https://demo.domain.com/app/test' 
4. After successfull login the callback request will forward you to 'https://demo.domain.com/test' 

### express-openid-connect version

2.16.0

### Express version

4.18.2

### Node.js version

18.11.18
